### ISSUE TITLE
storybook導入 + plugins

### ISSUE THREAD

**Issue by s-hirano-ist** [s-hirano-ist/dump-to-github#64]
ShadcnUIの各コンポーネントに対して、コンポーネントのtsxファイルと同一階層に`コンポーネント名.stories.tsx`形式のファイル名でstorybookのファイルを生成。

とりあえず1つのコンポーネントのstorybookを作れたらPR出してもらえると助かる。

- [ ] プラグインは適宜導入OK
- [ ] eslintの設定はMUST

`npx storybook@latest init`コマンド使えるはず！残りは公式docsみてみてー

**Comment by Inoue416** [comment]
上記の件、承知しました。
とりあえず1つ作れたら、PR投げます。

**Comment by Inoue416** [comment]
@s-hirano-ist 
自身で切ったブランチをプッシュしようとしたらPermission errorが出るので権限くれると助かります。

**Comment by s-hirano-ist** [comment]
> @s-hirano-ist 
> 
> 自身で切ったブランチをプッシュしようとしたらPermission errorが出るので権限くれると助かります。

@Inoue416 理解！
家帰ったらやっときます！

**Comment by s-hirano-ist** [comment]
> > @s-hirano-ist 
> > 
> > 自身で切ったブランチをプッシュしようとしたらPermission errorが出るので権限くれると助かります。
> 
> @Inoue416 理解！
> 家帰ったらやっときます！

さっき招待送った
@Inoue416
